os/slacker

- .gitignore
- .travis.yml
- tox.ini
```
$ pip install tox
...
$ tox
...
py26: commands succeeded
py27: commands succeeded
py33: commands succeeded
py34: commands succeeded
```
Passing Travis CI build: https://travis-ci.org/msabramo/slacker/builds/43786595
To turn on Travis CI for your repo, see http://docs.travis-ci.com/user/getting-started/
> Tox and travis

- slacker/__init__.py
requests has a built in method for handling http errors
http://docs.python-requests.org/en/latest/api/#requests.Response.raise_for_status
> use response.raise_for_status() instead of assert

- slacker/__init__.py
Default timeout of 5 minutes. Let timeout exceptions from requests
bubble up, rather than wrapping them.
> Support default timeout for API calls.

- slacker/__init__.py
Even though some methods are specifically set to make POST requests,
they still send the message payload entirely in params like a GET
request. The max length of a url is much lower than the 16K bytes that
Slack accepts in request bodies.
I just did a search & replace for params= inside self.post calls. I've manually tested chat.post_message, but not other methods.
> POST api payloads in the request body, not url

- README.rst
When sending a message without the `as_user` option, it does not use Bot's preferences as configured
When adding `as_user=True` though, it displays everything correctly.
> Update example: make bot send messages as user

- slacker/__init__.py
these two functions (`delete` and `update`) don't return the response from the slack api calls. I discovered this while attempting to check the response 'ok' key returned by slack.
> fixes chat delete and update not returning response

- slacker/__init__.py
"unreads" argument is supported in channels.history API.
https://api.slack.com/methods/channels.history
> Add "unreads" argument for channels.history API.

- slacker/__init__.py
The [chat.update](https://api.slack.com/methods/chat.update) call allows to edit the `attachments` list of a message. This PR adds an optional `attachments` kwarg to `Slacker.chat.update` which will be treated like its `postMessage` equivalent.
> Add support to update `attachments` of a message

- slacker/__init__.py
This change enables executing slash commands through the API. While it isn't documented, chat.command can be seen in use in the Slack web UI. `command` is the slash command to apply, for example `giphy` or `todo` or `catfact`. `text` is the query or arguments to the slash command.
> Added chat.command with basic functionality

- slacker/__init__.py
This was probably a copy/paste error.
> Use team.profile.get method for TeamProfile

- slacker/__init__.py
The source [documentation](https://github.com/ErikKalkoken/slackApiDoc/blob/master/users.admin.invite.md) to invite users to a team.
> Added undocumented users.admin.invite method

- slacker/__init__.py
When updating a message on slack there's a difference between not providing an attachments argument and providing an empty list. In the former case the attachments are left as is while providing an empty list updates the message to have no attachments.
With this patch the attachments will be json encoded also in the case when providing an empty list.
> make sure empty lists are also json encoded

- README.rst
- setup.py
- slacker/__init__.py
Added the ability to specify a proxy to API requests.
Useful when it is used in a script in a production environment without outside access and you cannot rely on environmental variables like http_proxy and https_proxy.
> Proxy requests

- README.rst
- slacker/__init__.py
Something went really wrong with passing proxy parameters.
- `Slacker.__init__` wasn't accepting proxy parameters despite the claims in the documentation.
- `__createProxies` was never called.
- `proxies` local variable was not defined.
- Unpythoniс casing was there.
> Fix proxy handling

- README.rst
- slacker/__init__.py
This addresses #100. 
`Slacker()` now optionally receives `requests.Session` object to run requests through. If not provided it uses `requests.get` or `requests.post` as before (these create a separate session for each api call resulting in https handshake every time).
Implementation is straightforward. `requests.get`/`requests.post` are effectively inlined to utilize user provided session object.
I'm getting 30% off from mean time to request Slack (a chat archiving crawler) and like 60% off from traffic volume (https overhead).
> Support connection pooling via requests.Session

- .travis.yml
PR #118 and #120 failed on travis, simply because the python version under test was not available in the container.
This changes the behavior to have travis explicitly install the required version and pass that version by getting the TOXENV from an automatically set environment variable.
> Specify required python versions a more travish way to make them work

- slacker/__init__.py
>  Add support for re-trying on Slack's 429 rate limited response after their suggested wait time. Default is no retries.

- slacker/__init__.py
I added the new method of [chat.getPermalink](https://api.slack.com/methods/chat.getPermalink) to Chat class.
Usage example
```
slack = Slacker('<your-slack-api-token-goes-here>')
response = slack.chat.get_permalink('<channel>', '<message_ts>')
```
Response example
```
{
"ok": true,
"channel": "C1H9RESGA",
"permalink": "https:\/\/ghostbusters.slack.com\/archives\/C1H9RESGA\/p135854651500008"
}
```
> Add the new method of chat.getPermalink

- slacker/__init__.py
Currently the file must exist on disk, however sometimes it's useful to use a file handle directly.
> Allow a file handle to be passed for files.upload

- slacker/__init__.py
This commit will add the ability to use blocks to Chat.post_message, Chat.update, and Chat.post_ephemeral.
Blocks are an optional ability to add visual effects using json-like structure. Slack has been pushing its use since early 2019.
This is an attempt to squash and re-PR this. I am the newbest, so if this doesn't work, I'm just gonna let someone else make the like, 25 character change to have this work.
> Add blocks support to Slacker
